---
heat_template_version: 2018-03-02
description: Top level HOT for creating instances.

resources:
  server_server1:
    type: OS::Nova::Server
    properties:
      name: server
      flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
      key_name: f762-keypair
      config_drive: True
      block_device_mapping_v2:
        - image: rhel-8.3
          delete_on_termination: true
          volume_size: 50
          boot_index: 0
      user_data_format: RAW
      user_data: |
        #cloud-config
        ssh_authorized_keys: "ssh-rsa AAAAB3NzaC1yc2 --<Output Omitted>--- devops@opentlc.com"
      networks:
        - network: f762-dev-network
      metadata:
        'AnsibleGroup': "apps"
      security_groups:
        - f762-DefaultSG
        - f762-HostSG
